const langs = {
  en: {
    home: "Home",
    about: "About us",
    features: "Features",
    solutian: "Solutian",
    english: "English",
    arabic: "Arabic",
    hoobank: "HooBank",
    discount: "20% DISCOUNT FOR 1 MONTH ACCOUNT1",
    gene: "The Next Generation Payment Method.",
    genep:
      "Our team of experts uses a methodology to identify the credit cards most likely to fit your needs. We examine annual percentage rates, annual fees.",
    nums1: "User Active",
    nums2: "TRUSTED BY COMPANY",
    nums3: "TRANSACTION",
    btn: "Get Started",
    serh2: "You do the business, we’ll handle the money.",
    serp: "With the right credit card, you can improve your financial life by building credit, earning rewards and saving money. But with hundreds of credit cards on the market.",
    serh3: "Rewards",
    serp1:
      "The best credit cards offer some tantalizing combinations of promotions and prizes",
    serh31: "100% Secured",
    serp2:
      "We take proactive steps make sure your information and transactions are secure.",
    serh32: "Balance Transfer",
    serp3:
      "A balance transfer credit card can save you a lot of money in interest charges.",
    billh2: "Last Transaction",
    billh31: "Dribbble Pro",
    billp7: "15 Days ago",
    bills3: "-$250,93",
    billh32: "Netflix",
    billp8: "4 Days ago",
    bills4: "-$250,93",
    billh33: "Manulife Cash",
    billp9: "4 Days ago",
    bills5: "-$250,93",
    billh4: "Paypal",
    billp: "Checkout",
    billp2: "Total",
    billh42: "$210",
    billa: "Change",
    billb: "Make Payment",
    billp3: "Great! Your Payment is succesfully.",
    billh3: "Easily control your billing & invoicing.",
    billp4:
      "Elit enim sed massa etiam. Mauris eu adipiscing ultrices ametodio aenean neque. Fusce ipsum orci rhoncus aliporttitor integer platea placerat.",
    billp5: "App Store",
    bills: "download on the",
    billp6: "Google Play",
    bills2: "Git It on",
    cardh2: "Find a better card deal in few easy steps.",
    cardp:
      "Arcu tortor, purus in mattis at sed integer faucibus. Aliquet quisaliquet eget mauris tortor.ç Aliquet ultrices ac, ametau.",
    cardb: "Get Started",
    cardh3: "Online Analysis",
    cards: "1 Month",
    cardp2: "$ 2,334,67 Income",
    cards2: "$ 5.31M Expenses",
    cardli: "Jan",
    cardli2: "Feb",
    cardli3: "Mar",
    cardli4: "Apr",
    cardli5: "May",
    cardli6: "Jun",
    cardli7: "Jul",
    cardh32: "Pay Method",
    cardh33: "Scan Credit Cards",
    cardp3: "Scan your credit card in 4 minutes.",
    peph3: "What people are saying about us",
    pepp: " Everything you need to accept card payments and grow your business anywhere on the planet.",
    peph4:
      "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.",
    peph5: "Herman Jensen",
    pepp2: "Founder & Leader",
    peph42:
      "Money makes your life easier. If you're lucky to have it, you're lucky",
    peph52: "Steve Mark",
    peph43:
      "It is usually people in the money business, finance, and international trade that are really rich.",
    peph53: "Kenn Gallagher",
    banh3: "Let’s try our service now!",
    banp: "Everything you need to accept card payments and grow your business anywhere on the planet.",
    bana: "Get Started",
    foota: "Content",
    foota2: "How it Works",
    foota3: "Create",
    foota4: "Explore",
    foota5: "Terms & Services",
    foota6: "Help Center",
    foota7: "Partners",
    foota8: "Suggestions",
    foota9: "Blog",
    foota10: "Newsletters",
    foota11: "Our Partner",
    foota12: "Become a Partner",
    footp: "A new way to make the payments easy, reliable and secure.",
    footh4: "Usefull Links",
    footh42: "Community",
    footh43: "Partner",
    footp2: "Copyright &copy; 2021 HooBank. All Rights Reserved.",
  },
  ar: {
    home: "الصفحة الرئيسية",
    about: "من نحن",
    features: "المتغيرات",
    solutian: "الحلول",
    english: "الانجليزية",
    arabic: "العربية",
    hoobank: "البنك الاتحادى",
    discount: "خصم 20% على حساب واحد لمدة شهر واحد",
    gene: "احدث طرق الدفع للجيل القادم.",
    genep:
      "يستخدم فريق الخبراء لدينا منهجية لتحديد بطاقات الائتمان التي من المرجح أن تناسب احتياجاتك. نحن نفحص معدلات النسبة السنوية والرسوم السنوية.",
    nums1: "مستخدم نشط",
    nums2: "موثوق به من قبل الشركة",
    nums3: "صفقة",
    btn: "ابدء الان",
    serh2: "أنت تقوم بالأعمال التجارية، ونحن سوف نتعامل مع المال.",
    serp: "باستخدام بطاقة الائتمان المناسبة، يمكنك تحسين حياتك المالية من خلال بناء الائتمان وكسب المكافآت وتوفير المال. ولكن مع وجود المئات من بطاقات الائتمان في السوق.",
    serh3: "المكافآت",
    serp1:
      "تقدم أفضل بطاقات الائتمان بعض المجموعات المثيرة من العروض الترويجية والجوائز",
    serh31: "مؤمن بنسبة 100%",
    serp2: "نحن نتخذ خطوات استباقية للتأكد من أمان معلوماتك ومعاملاتك.",
    serh32: "تحويل الرصيد",
    serp3:
      "يمكن أن توفر لك بطاقة الائتمان لتحويل الرصيد الكثير من المال في رسوم الفائدة.",
    billh2: "المعاملة الأخيرة",
    billh31: "دريببل برو",
    billp7: "منذ 15 يوما",
    bills3: "-250,93 دولارًا",
    billh32: "نيتفليكس",
    billp8: "منذ 4 أيام",
    bills4: "-250,93 دولارًا",
    billh33: "مانولايف كاش",
    billp9: "منذ 4 أيام",
    bills5: "-250,93 دولارًا",
    billh4: "باي بال",
    billp: "الدفع",
    billp2: "الاجمالى",
    billh42: "210 دولار",
    billa: "تبديل",
    billb: "قم بالدفع",
    billp3: "عظيم! تم الدفع بنجاح.",
    billh3: "التحكم بسهولة في الفواتير والفواتير الخاصة بك.",
    billp4:
      "يستخدم فريق الخبراء لدينا منهجية لتحديد بطاقات الائتمان التي من المرجح أن تناسب احتياجاتك. نحن نفحص معدلات النسبة السنوية والرسوم السنوية.",
    billp5: "متجر التطبيقات",
    bills: "تحميل على",
    billp6: "تطبيقات جوجل",
    bills2: "احصل عليه",
    cardh2: "يمكنك العثور على صفقة أفضل للبطاقة في بضع خطوات سهلة.",
    cardp:
      "يستخدم فريق الخبراء لدينا منهجية لتحديد بطاقات الائتمان التي من المرجح أن تناسب احتياجاتك. نحن نفحص معدلات النسبة السنوية والرسوم السنوية.",
    cardb: "ابدء الان",
    cardh3: "تحليل على الانترنت",
    cards: "شهر واحد",
    cardp2: "الدخل 2,334,67 دولار",
    cards2: "مصاريف 5.31 مليون دولار",
    cardli: "يناير",
    cardli2: "فبراير",
    cardli3: "مارس",
    cardli4: "ابريل",
    cardli5: "مايو",
    cardli6: "يونيو",
    cardli7: "يوليه",
    cardh32: "طريقة الدفع",
    cardh33: "مسح بطاقات الائتمان",
    cardp3: "قم بمسح بطاقة الائتمان الخاصة بك في 4 دقائق.",
    peph3: "ماذا يقول الناس عنا",
    pepp: "كل ما تحتاجه لقبول مدفوعات البطاقات وتنمية أعمالك في أي مكان على هذا الكوكب.",
    peph4:
      "المال ليس سوى أداة. سوف يأخذك إلى حيث تريد، لكنه لن يحل محلك كسائق.",
    peph5: "هيرمان جنسن",
    pepp2: "المؤسس والقائد",
    peph42:
      "المال يجعل حياتك أسهل. إذا كنت محظوظًا بالحصول عليه، فأنت كذلك محظوظ",
    peph52: "ستيف مارك",
    peph43:
      "عادةً ما يكون الأشخاص الذين يعملون في مجال المال والتمويل والتجارة الدولية هم الأغنياء حقًا.",
    peph53: "كين غالاغر",
    banh3: "دعونا نجرب خدمتنا الآن!",
    banp: "كل ما تحتاجه لقبول مدفوعات البطاقة وتنمية أعمالك في أي مكان على هذا الكوكب.",
    bana: "ابدء الان",
    foota: "المحتوى",
    foota2: "كيفية العمل",
    foota3: "انشاء",
    foota4: "استكشف",
    foota5: "الشروط والخدمات",
    foota6: "مركز المساعدة",
    foota7: "الشركاء",
    foota8: "اقتراحات",
    foota9: "مدونة",
    foota10: "النشرات الإخبارية",
    foota11: "شريكنا",
    foota12: "كن شريكا",
    footp: "طريقة جديدة لجعل المدفوعات سهلة وموثوقة وآمنة.",
    footh4: "روابط مفيدة",
    footh42: "مجتمع",
    footh43: "الشريك",
    footp2: "حقوق الطبع والنشر 2021 HooBank. كل الحقوق محفوظة.",
  },
};

export default langs;
